/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeRiderRouteImport } from './routes/become-rider'
import { Route as BecomeSellerRouteImport } from './routes/become-seller'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as ErrandsRouteImport } from './routes/errands'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoodRouteImport } from './routes/food'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as InternalAdminRouteImport } from './routes/internal-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MyProductsRouteImport } from './routes/my-products'
import { Route as MyStoresRouteImport } from './routes/my-stores'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as RiderWalletRouteImport } from './routes/rider-wallet'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellerWalletRouteImport } from './routes/seller-wallet'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StoreOrdersRouteImport } from './routes/store-orders'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as InternalAdminIndexRouteImport } from './routes/internal-admin.index'
import { Route as InternalAdminAccountRouteImport } from './routes/internal-admin.account'
import { Route as InternalAdminAnnouncementsRouteImport } from './routes/internal-admin.announcements'
import { Route as InternalAdminAuditRouteImport } from './routes/internal-admin.audit'
import { Route as InternalAdminCustomersRouteImport } from './routes/internal-admin.customers'
import { Route as InternalAdminDispatchRouteImport } from './routes/internal-admin.dispatch'
import { Route as InternalAdminOrdersRouteImport } from './routes/internal-admin.orders'
import { Route as InternalAdminPaymentMethodsRouteImport } from './routes/internal-admin.payment-methods'
import { Route as InternalAdminReportsRouteImport } from './routes/internal-admin.reports'
import { Route as InternalAdminRiderApplicationsRouteImport } from './routes/internal-admin.rider-applications'
import { Route as InternalAdminRidersRouteImport } from './routes/internal-admin.riders'
import { Route as InternalAdminSellersRouteImport } from './routes/internal-admin.sellers'
import { Route as InternalAdminSettingsRouteImport } from './routes/internal-admin.settings'
import { Route as InternalAdminStoreApplicationsRouteImport } from './routes/internal-admin.store-applications'
import { Route as InternalAdminTopupsRouteImport } from './routes/internal-admin.topups'
import { Route as InternalAdminUsersRouteImport } from './routes/internal-admin.users'
import { Route as InternalAdminWalletsRouteImport } from './routes/internal-admin.wallets'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRiderRoute = BecomeRiderRouteImport.update({
  id: '/become-rider',
  path: '/become-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeSellerRoute = BecomeSellerRouteImport.update({
  id: '/become-seller',
  path: '/become-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrandsRoute = ErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAdminRoute = InternalAdminRouteImport.update({
  id: '/internal-admin',
  path: '/internal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProductsRoute = MyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoresRoute = MyStoresRouteImport.update({
  id: '/my-stores',
  path: '/my-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderWalletRoute = RiderWalletRouteImport.update({
  id: '/rider-wallet',
  path: '/rider-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerWalletRoute = SellerWalletRouteImport.update({
  id: '/seller-wallet',
  path: '/seller-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/store-orders',
  path: '/store-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAdminIndexRoute = InternalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminAccountRoute = InternalAdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminAnnouncementsRoute =
  InternalAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => InternalAdminRoute,
  } as any)
const InternalAdminAuditRoute = InternalAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminCustomersRoute = InternalAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminDispatchRoute = InternalAdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminOrdersRoute = InternalAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminPaymentMethodsRoute =
  InternalAdminPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => InternalAdminRoute,
  } as any)
const InternalAdminReportsRoute = InternalAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminRiderApplicationsRoute =
  InternalAdminRiderApplicationsRouteImport.update({
    id: '/rider-applications',
    path: '/rider-applications',
    getParentRoute: () => InternalAdminRoute,
  } as any)
const InternalAdminRidersRoute = InternalAdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminSellersRoute = InternalAdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminSettingsRoute = InternalAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminStoreApplicationsRoute =
  InternalAdminStoreApplicationsRouteImport.update({
    id: '/store-applications',
    path: '/store-applications',
    getParentRoute: () => InternalAdminRoute,
  } as any)
const InternalAdminTopupsRoute = InternalAdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminUsersRoute = InternalAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => InternalAdminRoute,
} as any)
const InternalAdminWalletsRoute = InternalAdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => InternalAdminRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-rider': typeof BecomeRiderRoute
  '/become-seller': typeof BecomeSellerRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/errands': typeof ErrandsRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/groceries': typeof GroceriesRoute
  '/internal-admin': typeof InternalAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/my-products': typeof MyProductsRoute
  '/my-stores': typeof MyStoresRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRoute
  '/rider-wallet': typeof RiderWalletRoute
  '/seller': typeof SellerRoute
  '/seller-wallet': typeof SellerWalletRoute
  '/services': typeof ServicesRoute
  '/store-orders': typeof StoreOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/internal-admin/account': typeof InternalAdminAccountRoute
  '/internal-admin/announcements': typeof InternalAdminAnnouncementsRoute
  '/internal-admin/audit': typeof InternalAdminAuditRoute
  '/internal-admin/customers': typeof InternalAdminCustomersRoute
  '/internal-admin/dispatch': typeof InternalAdminDispatchRoute
  '/internal-admin/orders': typeof InternalAdminOrdersRoute
  '/internal-admin/payment-methods': typeof InternalAdminPaymentMethodsRoute
  '/internal-admin/reports': typeof InternalAdminReportsRoute
  '/internal-admin/rider-applications': typeof InternalAdminRiderApplicationsRoute
  '/internal-admin/riders': typeof InternalAdminRidersRoute
  '/internal-admin/sellers': typeof InternalAdminSellersRoute
  '/internal-admin/settings': typeof InternalAdminSettingsRoute
  '/internal-admin/store-applications': typeof InternalAdminStoreApplicationsRoute
  '/internal-admin/topups': typeof InternalAdminTopupsRoute
  '/internal-admin/users': typeof InternalAdminUsersRoute
  '/internal-admin/wallets': typeof InternalAdminWalletsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/internal-admin/': typeof InternalAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-rider': typeof BecomeRiderRoute
  '/become-seller': typeof BecomeSellerRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/errands': typeof ErrandsRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/groceries': typeof GroceriesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/my-products': typeof MyProductsRoute
  '/my-stores': typeof MyStoresRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRoute
  '/rider-wallet': typeof RiderWalletRoute
  '/seller': typeof SellerRoute
  '/seller-wallet': typeof SellerWalletRoute
  '/services': typeof ServicesRoute
  '/store-orders': typeof StoreOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/internal-admin/account': typeof InternalAdminAccountRoute
  '/internal-admin/announcements': typeof InternalAdminAnnouncementsRoute
  '/internal-admin/audit': typeof InternalAdminAuditRoute
  '/internal-admin/customers': typeof InternalAdminCustomersRoute
  '/internal-admin/dispatch': typeof InternalAdminDispatchRoute
  '/internal-admin/orders': typeof InternalAdminOrdersRoute
  '/internal-admin/payment-methods': typeof InternalAdminPaymentMethodsRoute
  '/internal-admin/reports': typeof InternalAdminReportsRoute
  '/internal-admin/rider-applications': typeof InternalAdminRiderApplicationsRoute
  '/internal-admin/riders': typeof InternalAdminRidersRoute
  '/internal-admin/sellers': typeof InternalAdminSellersRoute
  '/internal-admin/settings': typeof InternalAdminSettingsRoute
  '/internal-admin/store-applications': typeof InternalAdminStoreApplicationsRoute
  '/internal-admin/topups': typeof InternalAdminTopupsRoute
  '/internal-admin/users': typeof InternalAdminUsersRoute
  '/internal-admin/wallets': typeof InternalAdminWalletsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/internal-admin': typeof InternalAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-rider': typeof BecomeRiderRoute
  '/become-seller': typeof BecomeSellerRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRoute
  '/errands': typeof ErrandsRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/groceries': typeof GroceriesRoute
  '/internal-admin': typeof InternalAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/my-products': typeof MyProductsRoute
  '/my-stores': typeof MyStoresRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRoute
  '/rider-wallet': typeof RiderWalletRoute
  '/seller': typeof SellerRoute
  '/seller-wallet': typeof SellerWalletRoute
  '/services': typeof ServicesRoute
  '/store-orders': typeof StoreOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/internal-admin/account': typeof InternalAdminAccountRoute
  '/internal-admin/announcements': typeof InternalAdminAnnouncementsRoute
  '/internal-admin/audit': typeof InternalAdminAuditRoute
  '/internal-admin/customers': typeof InternalAdminCustomersRoute
  '/internal-admin/dispatch': typeof InternalAdminDispatchRoute
  '/internal-admin/orders': typeof InternalAdminOrdersRoute
  '/internal-admin/payment-methods': typeof InternalAdminPaymentMethodsRoute
  '/internal-admin/reports': typeof InternalAdminReportsRoute
  '/internal-admin/rider-applications': typeof InternalAdminRiderApplicationsRoute
  '/internal-admin/riders': typeof InternalAdminRidersRoute
  '/internal-admin/sellers': typeof InternalAdminSellersRoute
  '/internal-admin/settings': typeof InternalAdminSettingsRoute
  '/internal-admin/store-applications': typeof InternalAdminStoreApplicationsRoute
  '/internal-admin/topups': typeof InternalAdminTopupsRoute
  '/internal-admin/users': typeof InternalAdminUsersRoute
  '/internal-admin/wallets': typeof InternalAdminWalletsRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/internal-admin/': typeof InternalAdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-rider'
    | '/become-seller'
    | '/checkout'
    | '/contact'
    | '/customer'
    | '/errands'
    | '/faq'
    | '/food'
    | '/groceries'
    | '/internal-admin'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/my-products'
    | '/my-stores'
    | '/pharmacy'
    | '/register'
    | '/rider'
    | '/rider-wallet'
    | '/seller'
    | '/seller-wallet'
    | '/services'
    | '/store-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/internal-admin/account'
    | '/internal-admin/announcements'
    | '/internal-admin/audit'
    | '/internal-admin/customers'
    | '/internal-admin/dispatch'
    | '/internal-admin/orders'
    | '/internal-admin/payment-methods'
    | '/internal-admin/reports'
    | '/internal-admin/rider-applications'
    | '/internal-admin/riders'
    | '/internal-admin/sellers'
    | '/internal-admin/settings'
    | '/internal-admin/store-applications'
    | '/internal-admin/topups'
    | '/internal-admin/users'
    | '/internal-admin/wallets'
    | '/order/$orderId'
    | '/store/$storeId'
    | '/internal-admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-rider'
    | '/become-seller'
    | '/checkout'
    | '/contact'
    | '/customer'
    | '/errands'
    | '/faq'
    | '/food'
    | '/groceries'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/my-products'
    | '/my-stores'
    | '/pharmacy'
    | '/register'
    | '/rider'
    | '/rider-wallet'
    | '/seller'
    | '/seller-wallet'
    | '/services'
    | '/store-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/internal-admin/account'
    | '/internal-admin/announcements'
    | '/internal-admin/audit'
    | '/internal-admin/customers'
    | '/internal-admin/dispatch'
    | '/internal-admin/orders'
    | '/internal-admin/payment-methods'
    | '/internal-admin/reports'
    | '/internal-admin/rider-applications'
    | '/internal-admin/riders'
    | '/internal-admin/sellers'
    | '/internal-admin/settings'
    | '/internal-admin/store-applications'
    | '/internal-admin/topups'
    | '/internal-admin/users'
    | '/internal-admin/wallets'
    | '/order/$orderId'
    | '/store/$storeId'
    | '/internal-admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-rider'
    | '/become-seller'
    | '/checkout'
    | '/contact'
    | '/customer'
    | '/errands'
    | '/faq'
    | '/food'
    | '/groceries'
    | '/internal-admin'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/my-products'
    | '/my-stores'
    | '/pharmacy'
    | '/register'
    | '/rider'
    | '/rider-wallet'
    | '/seller'
    | '/seller-wallet'
    | '/services'
    | '/store-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/internal-admin/account'
    | '/internal-admin/announcements'
    | '/internal-admin/audit'
    | '/internal-admin/customers'
    | '/internal-admin/dispatch'
    | '/internal-admin/orders'
    | '/internal-admin/payment-methods'
    | '/internal-admin/reports'
    | '/internal-admin/rider-applications'
    | '/internal-admin/riders'
    | '/internal-admin/sellers'
    | '/internal-admin/settings'
    | '/internal-admin/store-applications'
    | '/internal-admin/topups'
    | '/internal-admin/users'
    | '/internal-admin/wallets'
    | '/order/$orderId'
    | '/store/$storeId'
    | '/internal-admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeRiderRoute: typeof BecomeRiderRoute
  BecomeSellerRoute: typeof BecomeSellerRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomerRoute: typeof CustomerRoute
  ErrandsRoute: typeof ErrandsRoute
  FaqRoute: typeof FaqRoute
  FoodRoute: typeof FoodRoute
  GroceriesRoute: typeof GroceriesRoute
  InternalAdminRoute: typeof InternalAdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  MyProductsRoute: typeof MyProductsRoute
  MyStoresRoute: typeof MyStoresRoute
  PharmacyRoute: typeof PharmacyRoute
  RegisterRoute: typeof RegisterRoute
  RiderRoute: typeof RiderRoute
  RiderWalletRoute: typeof RiderWalletRoute
  SellerRoute: typeof SellerRoute
  SellerWalletRoute: typeof SellerWalletRoute
  ServicesRoute: typeof ServicesRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-rider': {
      id: '/become-rider'
      path: '/become-rider'
      fullPath: '/become-rider'
      preLoaderRoute: typeof BecomeRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-seller': {
      id: '/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof BecomeSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errands': {
      id: '/errands'
      path: '/errands'
      fullPath: '/errands'
      preLoaderRoute: typeof ErrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-admin': {
      id: '/internal-admin'
      path: '/internal-admin'
      fullPath: '/internal-admin'
      preLoaderRoute: typeof InternalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-products': {
      id: '/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof MyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-stores': {
      id: '/my-stores'
      path: '/my-stores'
      fullPath: '/my-stores'
      preLoaderRoute: typeof MyStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider-wallet': {
      id: '/rider-wallet'
      path: '/rider-wallet'
      fullPath: '/rider-wallet'
      preLoaderRoute: typeof RiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-wallet': {
      id: '/seller-wallet'
      path: '/seller-wallet'
      fullPath: '/seller-wallet'
      preLoaderRoute: typeof SellerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-orders': {
      id: '/store-orders'
      path: '/store-orders'
      fullPath: '/store-orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-admin/': {
      id: '/internal-admin/'
      path: '/'
      fullPath: '/internal-admin/'
      preLoaderRoute: typeof InternalAdminIndexRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/account': {
      id: '/internal-admin/account'
      path: '/account'
      fullPath: '/internal-admin/account'
      preLoaderRoute: typeof InternalAdminAccountRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/announcements': {
      id: '/internal-admin/announcements'
      path: '/announcements'
      fullPath: '/internal-admin/announcements'
      preLoaderRoute: typeof InternalAdminAnnouncementsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/audit': {
      id: '/internal-admin/audit'
      path: '/audit'
      fullPath: '/internal-admin/audit'
      preLoaderRoute: typeof InternalAdminAuditRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/customers': {
      id: '/internal-admin/customers'
      path: '/customers'
      fullPath: '/internal-admin/customers'
      preLoaderRoute: typeof InternalAdminCustomersRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/dispatch': {
      id: '/internal-admin/dispatch'
      path: '/dispatch'
      fullPath: '/internal-admin/dispatch'
      preLoaderRoute: typeof InternalAdminDispatchRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/orders': {
      id: '/internal-admin/orders'
      path: '/orders'
      fullPath: '/internal-admin/orders'
      preLoaderRoute: typeof InternalAdminOrdersRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/payment-methods': {
      id: '/internal-admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/internal-admin/payment-methods'
      preLoaderRoute: typeof InternalAdminPaymentMethodsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/reports': {
      id: '/internal-admin/reports'
      path: '/reports'
      fullPath: '/internal-admin/reports'
      preLoaderRoute: typeof InternalAdminReportsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/rider-applications': {
      id: '/internal-admin/rider-applications'
      path: '/rider-applications'
      fullPath: '/internal-admin/rider-applications'
      preLoaderRoute: typeof InternalAdminRiderApplicationsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/riders': {
      id: '/internal-admin/riders'
      path: '/riders'
      fullPath: '/internal-admin/riders'
      preLoaderRoute: typeof InternalAdminRidersRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/sellers': {
      id: '/internal-admin/sellers'
      path: '/sellers'
      fullPath: '/internal-admin/sellers'
      preLoaderRoute: typeof InternalAdminSellersRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/settings': {
      id: '/internal-admin/settings'
      path: '/settings'
      fullPath: '/internal-admin/settings'
      preLoaderRoute: typeof InternalAdminSettingsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/store-applications': {
      id: '/internal-admin/store-applications'
      path: '/store-applications'
      fullPath: '/internal-admin/store-applications'
      preLoaderRoute: typeof InternalAdminStoreApplicationsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/topups': {
      id: '/internal-admin/topups'
      path: '/topups'
      fullPath: '/internal-admin/topups'
      preLoaderRoute: typeof InternalAdminTopupsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/users': {
      id: '/internal-admin/users'
      path: '/users'
      fullPath: '/internal-admin/users'
      preLoaderRoute: typeof InternalAdminUsersRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/internal-admin/wallets': {
      id: '/internal-admin/wallets'
      path: '/wallets'
      fullPath: '/internal-admin/wallets'
      preLoaderRoute: typeof InternalAdminWalletsRouteImport
      parentRoute: typeof InternalAdminRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InternalAdminRouteChildren {
  InternalAdminAccountRoute: typeof InternalAdminAccountRoute
  InternalAdminAnnouncementsRoute: typeof InternalAdminAnnouncementsRoute
  InternalAdminAuditRoute: typeof InternalAdminAuditRoute
  InternalAdminCustomersRoute: typeof InternalAdminCustomersRoute
  InternalAdminDispatchRoute: typeof InternalAdminDispatchRoute
  InternalAdminOrdersRoute: typeof InternalAdminOrdersRoute
  InternalAdminPaymentMethodsRoute: typeof InternalAdminPaymentMethodsRoute
  InternalAdminReportsRoute: typeof InternalAdminReportsRoute
  InternalAdminRiderApplicationsRoute: typeof InternalAdminRiderApplicationsRoute
  InternalAdminRidersRoute: typeof InternalAdminRidersRoute
  InternalAdminSellersRoute: typeof InternalAdminSellersRoute
  InternalAdminSettingsRoute: typeof InternalAdminSettingsRoute
  InternalAdminStoreApplicationsRoute: typeof InternalAdminStoreApplicationsRoute
  InternalAdminTopupsRoute: typeof InternalAdminTopupsRoute
  InternalAdminUsersRoute: typeof InternalAdminUsersRoute
  InternalAdminWalletsRoute: typeof InternalAdminWalletsRoute
  InternalAdminIndexRoute: typeof InternalAdminIndexRoute
}

const InternalAdminRouteChildren: InternalAdminRouteChildren = {
  InternalAdminAccountRoute: InternalAdminAccountRoute,
  InternalAdminAnnouncementsRoute: InternalAdminAnnouncementsRoute,
  InternalAdminAuditRoute: InternalAdminAuditRoute,
  InternalAdminCustomersRoute: InternalAdminCustomersRoute,
  InternalAdminDispatchRoute: InternalAdminDispatchRoute,
  InternalAdminOrdersRoute: InternalAdminOrdersRoute,
  InternalAdminPaymentMethodsRoute: InternalAdminPaymentMethodsRoute,
  InternalAdminReportsRoute: InternalAdminReportsRoute,
  InternalAdminRiderApplicationsRoute: InternalAdminRiderApplicationsRoute,
  InternalAdminRidersRoute: InternalAdminRidersRoute,
  InternalAdminSellersRoute: InternalAdminSellersRoute,
  InternalAdminSettingsRoute: InternalAdminSettingsRoute,
  InternalAdminStoreApplicationsRoute: InternalAdminStoreApplicationsRoute,
  InternalAdminTopupsRoute: InternalAdminTopupsRoute,
  InternalAdminUsersRoute: InternalAdminUsersRoute,
  InternalAdminWalletsRoute: InternalAdminWalletsRoute,
  InternalAdminIndexRoute: InternalAdminIndexRoute,
}

const InternalAdminRouteWithChildren = InternalAdminRoute._addFileChildren(
  InternalAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeRiderRoute: BecomeRiderRoute,
  BecomeSellerRoute: BecomeSellerRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomerRoute: CustomerRoute,
  ErrandsRoute: ErrandsRoute,
  FaqRoute: FaqRoute,
  FoodRoute: FoodRoute,
  GroceriesRoute: GroceriesRoute,
  InternalAdminRoute: InternalAdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  MyProductsRoute: MyProductsRoute,
  MyStoresRoute: MyStoresRoute,
  PharmacyRoute: PharmacyRoute,
  RegisterRoute: RegisterRoute,
  RiderRoute: RiderRoute,
  RiderWalletRoute: RiderWalletRoute,
  SellerRoute: SellerRoute,
  SellerWalletRoute: SellerWalletRoute,
  ServicesRoute: ServicesRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
